DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS categories;

create table if not exists categories (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 name VARCHAR(50) not null unique
);

create table if not exists tasks (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(50) not null,
  category_id integer not null,
  due_date DATE not null,
  current_status VARCHAR(50) not null,
  constraint fk_tasks_category foreign key (category_id) references categories(id) on delete cascade
);